stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/car_data.csv
    outs:
    - data/raw/car_data.csv

  preprocessing:
    cmd: python src/preprocessing.py --config=params.yaml
    deps:
    - src/get_data.py
    - data_given/car_data.csv
    outs:
    - data/raw/udatedCar_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/udatedCar_data.csv
    outs:
    - data/processed/train_car_data.csv
    - data/processed/test_car_data.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_car_data.csv
    - data/processed/test_car_data.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib